[package]
name = "simple_escrow_contract"
authors = [""]
compiler_version = ">=0.25.0"
type = "contract"

[dependencies]
aztec = { path = "../../../aztec-nr/aztec" }
escrowable_token = { path = "../escrowable_token_contract" }